from functions2 import *
import tarfile
import json
import random

########################################################################################
# This file generates a json file containing a big next word dictionary for all reviews in the tarfile.
# It loads the next word dictionaries from each review individually generated by 'data_gen.py' and
# updates them using the update_nwd function from 'functions2.py'.
########################################################################################

########################################################################################
# Opens the json file with all the next word dictionaries from individual reviews
########################################################################################

f = open('next-word-vecs-2.json')
nwd = json.load(f)

########################################################################################
# Initializes the big dictionary as nw_dict and combines the individual dictionaries from nwd
########################################################################################

nw_dict = {}
for key in nwd.keys():
    temp_dict = nwd[key]
    nw_dict = update_nwd(temp_dict, nw_dict)

f.close()

########################################################################################
# Writes the json file with the big dictionary from all the reviews
########################################################################################


json = json.dumps(nw_dict)
f = open('next-word-vecs-3.json', 'w')
f.write(json)
f.close()

